### ISSUE TITLE
希望查询后增加返回sess，服务端缓存sess或其他cookie/token方便短期内免登录查询

### ISSUE THREAD

**Issue by imldy** [zscorpio/OpenAI-Tool#1]
**理由**

增加返回sess：方便其他程序直接调用官方查余额接口（`/dashboard/billing/credit_grants`、`/dashboard/billing/usage`）

服务端缓存身份信息：减少登录次数，免登录过程快速返回结果

相关截图：

![image](https://github.com/zscorpio/OpenAI-Tool/assets/53949747/0ba2f9f7-fd35-4edb-869f-a140cb07d49c)

**Comment by zscorpio** [comment]
恩好的, 这样的话, 那我今天再优化下, 可以存到本地cache, 下次直接用缓存, 免得登陆

**Comment by zscorpio** [comment]
已增加
