### ISSUE TITLE
Cannot submit on Login button

### ISSUE THREAD

**Issue by fexli** [zscorpio/OpenAI-Tool#3]
error console:
```
TimeoutError: Waiting for selector `.launcher-menu` failed: Waiting failed: 30000ms exceeded
    at Timeout.<anonymous> (~/Desktop/OpenAI-Tool-main/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:59:37)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```
using headless=false mode found that the login page was stuck(after enter password)
<img width="415" alt="截屏2023-09-28 12 42 08" src="https://github.com/zscorpio/OpenAI-Tool/assets/62332061/a8d85778-da7a-4787-b09e-a78fd4f6d848">

**Comment by fexli** [comment]
chrome 测试版 v117.0.5938.92
on MacOS Ventura 13.4.1

**Comment by zscorpio** [comment]
I hava add a sleep before click login button, already pushed, you can pull and try again

**Comment by fexli** [comment]
I have also noticed that this may be caused by network latency. Thank you for fixing it!
